import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Globe, Eye, EyeOff, AlertCircle, Loader2, Sparkles, Check } from "lucide-react";
import useAuth from "../hooks/useAuth";

const Benefit = ({ text }) => (
  <div className="flex items-center gap-2.5 text-sm text-slate-400">
    <div className="w-4 h-4 rounded-full bg-teal-500/20 border border-teal-500/40 flex items-center justify-center shrink-0">
      <Check size={10} className="text-teal-400" />
    </div>
    {text}
  </div>
);

const SignupPage = () => {
  const { signup } = useAuth();
  const navigate   = useNavigate();

  const [formData, setFormData] = useState({ name:"", email:"", password:"", confirmPassword:"" });
  const [showPw, setShowPw]     = useState(false);
  const [error, setError]       = useState("");
  const [loading, setLoading]   = useState(false);

  const handleChange = (e) => {
    setFormData(p => ({ ...p, [e.target.name]: e.target.value }));
    if (error) setError("");
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!formData.name.trim())                        return setError("Name is required");
    if (formData.password.length < 6)                 return setError("Password must be at least 6 characters");
    if (formData.password !== formData.confirmPassword) return setError("Passwords do not match");
    setLoading(true);
    try {
      await signup(formData.name.trim(), formData.email, formData.password);
      navigate("/dashboard");
    } catch (err) {
      setError(err.response?.data?.message || "Signup failed. Please try again.");
    } finally { setLoading(false); }
  };

  return (
    <div className="min-h-screen mesh-bg flex">
      {/* ── Left panel (hidden on mobile) ─────────────────────── */}
      <div className="hidden lg:flex flex-col justify-between w-[420px] shrink-0 border-r border-white/[0.06] p-12">
        <Link to="/" className="flex items-center gap-2.5">
          <div className="w-8 h-8 bg-teal-500 rounded-lg flex items-center justify-center">
            <Globe size={16} className="text-slate-950" strokeWidth={2.5} />
          </div>
          <span className="font-display text-lg text-white">TravelGen</span>
        </Link>

        <div>
          <div className="inline-flex items-center gap-2 glass text-teal-300 text-xs px-3 py-1.5 rounded-full mb-6 border border-teal-500/20">
            <Sparkles size={11} /> AI-powered travel planning
          </div>
          <h2 className="font-display text-4xl text-white leading-snug mb-4">
            Start planning<br />smarter trips
          </h2>
          <p className="text-slate-400 text-sm leading-relaxed mb-8">
            Join thousands of travelers using TravelGen AI to build personalized itineraries in seconds.
          </p>
          <div className="space-y-3">
            <Benefit text="Full day-by-day itinerary generated by Gemini AI" />
            <Benefit text="Budget breakdown for every trip" />
            <Benefit text="Save and revisit all your plans" />
            <Benefit text="Dietary & interest preferences respected" />
          </div>
        </div>

        <p className="text-xs text-slate-600">© 2025 TravelGen AI</p>
      </div>

      {/* ── Right panel (form) ────────────────────────────────── */}
      <div className="flex-1 flex items-center justify-center px-4 py-12">
        <div className="w-full max-w-sm animate-fade-up">
          {/* Mobile logo */}
          <Link to="/" className="flex items-center gap-2 mb-8 lg:hidden">
            <div className="w-7 h-7 bg-teal-500 rounded-lg flex items-center justify-center">
              <Globe size={14} className="text-slate-950" />
            </div>
            <span className="font-display text-base text-white">TravelGen</span>
          </Link>

          <h1 className="font-display text-2xl text-white mb-1">Create your account</h1>
          <p className="text-slate-400 text-sm mb-7">Already have one? <Link to="/login" className="text-teal-400 hover:text-teal-300">Log in</Link></p>

          {error && (
            <div className="flex items-center gap-2 bg-red-950/40 border border-red-800/60 text-red-300 text-sm rounded-xl px-4 py-3 mb-5">
              <AlertCircle size={15} className="shrink-0" />{error}
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-4">
            {[
              { name:"name",            type:"text",     placeholder:"Alex Johnson",      label:"Full name"       },
              { name:"email",           type:"email",    placeholder:"alex@example.com",  label:"Email address"   },
            ].map(({ name, type, placeholder, label }) => (
              <div key={name}>
                <label className="block text-xs font-medium text-slate-400 mb-1.5">{label}</label>
                <input type={type} name={name} value={formData[name]}
                  onChange={handleChange} placeholder={placeholder} required
                  className="input-field" />
              </div>
            ))}

            {["password","confirmPassword"].map((field, i) => (
              <div key={field}>
                <label className="block text-xs font-medium text-slate-400 mb-1.5">
                  {i === 0 ? "Password" : "Confirm password"}
                </label>
                <div className="relative">
                  <input type={showPw ? "text" : "password"} name={field}
                    value={formData[field]} onChange={handleChange}
                    placeholder={i === 0 ? "Min. 6 characters" : "Re-enter password"}
                    required className="input-field pr-10" />
                  {i === 0 && (
                    <button type="button" onClick={() => setShowPw(!showPw)}
                      className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500 hover:text-slate-300 transition-colors">
                      {showPw ? <EyeOff size={15} /> : <Eye size={15} />}
                    </button>
                  )}
                </div>
              </div>
            ))}

            <button type="submit" disabled={loading}
              className="btn-teal w-full py-3 text-sm flex items-center justify-center gap-2 mt-2 disabled:opacity-50 disabled:cursor-not-allowed">
              {loading ? <><Loader2 size={15} className="animate-spin" /> Creating account…</> : "Create account"}
            </button>
          </form>
        </div>
      </div>
    </div>
  );
};

export default SignupPage;